apiVersion: v2
name: service-a
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"


maintainers:
  - name: Jose Reynoso
    email: reynosojose2005@gmail.com
    url: "https://www.linkedin.com/in/jose-reynoso-52b14a236/"
    description: "Arquitecto de sistemas en la nube, especialista en Kubernetes"

sources:
  - https://github.com/evil-cloud/resillience-poc-service-a-app

keywords:
  - fastapi
  - python
  - circuit-breaker
  - redis
  - kubernetes

annotations:
  "helm.sh/display-name": "Service A con Circuit Breaker"
  "helm.sh/category": "Microservices"
